DROP TABLE HISTORIES;
CREATE TABLE HISTORIES
(
    HISTORY_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(30 BYTE) NOT NULL,
    KEYWORD VARCHAR2(100 BYTE) NOT NULL,
    ACTION_DAY DATE
);
DROP SEQUENCE HISTORY_SEQ;
CREATE SEQUENCE HISTORY_SEQ NOCACHE;
INSERT INTO HISTORIES VALUES(HISTORY_SEQ.NEXTVAL, 'USER1', '날씨', '2000-05-01');
INSERT INTO HISTORIES VALUES(HISTORY_SEQ.NEXTVAL, 'USER2', '게임', '2000-05-05');
INSERT INTO HISTORIES VALUES(HISTORY_SEQ.NEXTVAL, 'USER1', '운동', '2000-05-04');
INSERT INTO HISTORIES VALUES(HISTORY_SEQ.NEXTVAL, 'USER2', '유럽', '2000-05-12');
INSERT INTO HISTORIES VALUES(HISTORY_SEQ.NEXTVAL, 'USER2', '여행', '2000-05-15');
COMMIT;