CREATE TABLE MOVIE(
    NO NUMBER NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(100 BYTE),
    GENRE VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(500 BYTE),
    STAR NUMBER
);

CREATE SEQUENCE MOVIE_SEQ;
INSERT INTO MOVIE
VALUES(MOVIE_SEQ.NEXTVAL, '엽기적인 그녀', '코미디', '견우야 미안해', 4);

COMMIT;